# Generated by Django 4.2.2 on 2023-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=20)),
                ('eml', models.EmailField(max_length=254)),
                ('fnm', models.CharField(max_length=20)),
                ('mnm', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=20)),
                ('cl', models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
                ('adr', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
