# Generated by Django 4.2.2 on 2023-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('numb', models.CharField(max_length=20)),
                ('clss', models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
                ('pswd', models.CharField(max_length=20)),
            ],
        ),
    ]
