# Generated by Django 4.2.2 on 2023-09-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='asgmntmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su', models.CharField(max_length=20)),
                ('ano', models.CharField(max_length=20)),
                ('asg', models.ImageField(upload_to='smsapp/static')),
            ],
        ),
    ]
