# Generated by Django 4.2.2 on 2023-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0004_asgmntmodel1_delete_asgmntmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='asgmntmodel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla', models.CharField(max_length=20)),
                ('su', models.CharField(max_length=20)),
                ('ano', models.CharField(max_length=20)),
                ('due', models.CharField(max_length=20)),
                ('asg', models.ImageField(upload_to='smsapp/static')),
            ],
        ),
        migrations.DeleteModel(
            name='asgmntmodel1',
        ),
    ]
