# Generated by Django 4.2.2 on 2023-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0006_subasgmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=20)),
                ('cl', models.CharField(max_length=20)),
                ('tlm', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('ccam', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('psm', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('hfm', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('itm', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('ctm', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('cfm', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('llm', models.CharField(choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], max_length=20)),
                ('sgm', models.CharField(max_length=100)),
            ],
        ),
    ]
