# Generated by Django 4.2.2 on 2023-09-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0007_reviewmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='pnotesmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla', models.CharField(max_length=20)),
                ('su', models.CharField(max_length=20)),
                ('cno', models.CharField(max_length=20)),
                ('nt', models.ImageField(upload_to='smsapp/static')),
            ],
        ),
    ]
